### ISSUE TITLE
Clicking upload without selecting a file still gives you a uuid on ur upload page

### ISSUE THREAD

**Issue by huntmj01** [aneeshraman97/CS372GroupProject#2]
No file selected:
![image](https://user-images.githubusercontent.com/10147954/33570854-30762cf0-d8fc-11e7-87a4-f42c14e3b0f1.png)

Still get a uuid:
![image](https://user-images.githubusercontent.com/10147954/33570927-6ec2630c-d8fc-11e7-93ae-fc6bd22648c1.png)

With an error:
> Warning: file_get_contents(): Filename cannot be empty in /home/ubuntu/workspace/project/CS372GroupProject/database.php on line 66 Call Stack: 0.0004 239144 1. {main}() /home/ubuntu/workspace/project/CS372GroupProject/ur-user.php:0 0.2459 248920 2. addFile() /home/ubuntu/workspace/project/CS372GroupProject/ur-user.php:86 0.2459 248968 3. file_get_contents() /home/ubuntu/workspace/project/CS372GroupProject/database.php:66

**Comment by staujd02** [comment]
This should be resolved, considering this is a side effect of a blank upload. Which has already been resolved if I am not mistaken.

**Comment by huntmj01** [comment]
@staujd02 Nice! It no longer gives the user a uuid.... but can you use sweet alerts to display an error message? Right now the page just blinks.

**Comment by staujd02** [comment]
No problem @MasterProgrammer200, just pushed a sweet alert addition to the page.

**Comment by huntmj01** [comment]
@staujd02 SWEET
