### ISSUE TITLE
Improve UI on sign up page

### ISSUE THREAD

**Issue by huntmj01** [aneeshraman97/CS372GroupProject#3]
![image](https://user-images.githubusercontent.com/10147954/33571030-c47dd13c-d8fc-11e7-9610-c0f3e64aeff4.png)

I've had a few of my friends try out our site and they were confused with 
1. The sign up at the top of the page. Can we have a button for it?
2. The icon beside First and Last Name is a letter so they were entering their email.
3. Once a user clicks Sign Up, they can't go back to the login page.

**Comment by staujd02** [comment]
Done and Done, I opted for the middle ground and made the top text a toggle...

**Comment by huntmj01** [comment]
@staujd02 Looks great!
