### ISSUE TITLE
Signup does not work

### ISSUE THREAD

**Issue by huntmj01** [aneeshraman97/CS372GroupProject#4]
![image](https://user-images.githubusercontent.com/10147954/33571241-72220d58-d8fd-11e7-9eb2-2a3028d66d4b.png)

I get the following error upon trying to sign up:

> The password and/or username you provided was not found.

**Comment by staujd02** [comment]
I have no idea what caused this error. I tried one or more things, and it started working again. Please try to replicate the situation, and then provide more details such as console errors or execution.

**Comment by huntmj01** [comment]
Hmmm seems to be working for me too.  I'm closing this one for now. I'll let you know if it happens again.
