### ISSUE TITLE
Error when trying to download a file that has been deleted

### ISSUE THREAD

**Issue by huntmj01** [aneeshraman97/CS372GroupProject#5]
The file with this uuid has been deleted:

![image](https://user-images.githubusercontent.com/10147954/33571869-5994bae0-d8ff-11e7-801c-3be184091ef1.png)

When I try to download it I get this error:

> Cannot add or update a child row: a foreign key constraint fails (`docdashDB`.`transactions`, CONSTRAINT `fk_file_id` FOREIGN KEY (`file_id`) REFERENCES `files` (`id`) ON DELETE SET NULL)

**Comment by staujd02** [comment]
This should be fixed now, Please test it and I will then close it.

**Comment by huntmj01** [comment]
@staujd02 well it doesn't throw an error anymore... but it does take me to a blank page.... can you have a redirect the user back to the download page if the user is not found? No errors in the console.

![image](https://user-images.githubusercontent.com/10147954/33575948-47009ed2-d90c-11e7-90b1-34766f443d1e.png)

**Comment by staujd02** [comment]
Please dump your cache and do a hard reload @MasterProgrammer200, It should redirect, it has to do with the old javascript in your browser...

**Comment by huntmj01** [comment]
Gotcha... refreshing did the trick.
